### ISSUE TITLE
AAF adapter doesn't get the Timeline global_start_time

### ISSUE THREAD

**Issue by jminor** [PixarAnimationStudios/OpenTimelineIO#398]
If your AAF has starting timecode, the resulting OTIO should hold that in global_start_time.

**Comment by andrewmoore-nz** [comment]
@jminor Any progress made with this one?

Now that we can read our AAFs properly, I've been able to do some testing on some fairly heavy-duty audio AAFs from a recent film project. The one I'm looking at at the moment - reel eight of this project - doesn't carry any information regarding the start time i.e. no indication that the timeline should start at `08:00:00:00`.

Is this perhaps something that could belong in the track/stack source_range?

**Comment by jminor** [comment]
Addressed by #478

**Comment by jminor** [comment]
Fixed in #478

**Comment by andrewmoore-nz** [comment]
Hey @jminor,

This is still an issue in AAFs coming from Premiere, as the `global_start_time` is simply coming through in the OTIO as `null`. The following AAF should start at 05:00:00:00, but the start time isn't recognized when using the latest OTIO PyAAF commits.  

[FullTestSeq_v02_TimeshiftExport_5hours.aaf.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/3185013/FullTestSeq_v02_TimeshiftExport_5hours.aaf.zip)

I haven't been able to test confirm this with any of our AAFs from Media Composer because currently OTIO is not able to read any of them due to the `CannotComputeAvailableRangeError` addressed in #484 .
