### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by stijncalis** [PixarAnimationStudios/OpenTimelineIO#681]
Hi guys,

I've seem to be getting the same error across three different Windows-pc's when trying to run otioview or when import opentimelineio in Python. I ran pip install opentimelineio and PySide2.
Is this a known issue?

Thank you for your time
```
Traceback (most recent call last):
  File "C:\Python37\Scripts\otioview-script.py", line 11, in <module>
    load_entry_point('OpenTimelineIO==0.12.0', 'console_scripts', 'otioview')()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python37\lib\site-packages\opentimelineview\__init__.py", line 27, in <module>
    from . import (
  File "c:\python37\lib\site-packages\opentimelineview\details_widget.py", line 27, in <module>
    import opentimelineio as otio
  File "c:\python37\lib\site-packages\opentimelineio\__init__.py", line 35, in <module>
    from . import (
  File "c:\python37\lib\site-packages\opentimelineio\opentime.py", line 1, in <module>
    from . _opentime import ( # noqa
ImportError: DLL load failed: The specified module could not be found.

```

**Comment by meshula** [comment]
Hi there! You are right. Can you take a look at issue https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/667 please? If you move the two files I mention as I describe, otio will work for you, while we look at the installation script.

**Comment by stijncalis** [comment]
@meshula Once again, thanks! I can finally start, I'm even more excited now

**Comment by ssteinbach** [comment]
Sounds like this is resolved, closing.  Thanks!

**Comment by JerryKon** [comment]
I am still getting this problem. And cannot find the way to solve this in #667 . I'm using the 0.13.0,python 2.7.
